### Configuration for training the Behavior Transformer using the PushT dataset ###

# Dataset parameters
[dataset]
seq_len = 10        # Context/sequence-length for each sample and Transformer blocks
stride = 1          # Stride for sampling sequences
device = "cuda"     # Device to move observations and actions to after sampling


# Dataloading parameters
[dataloader]
batch_size = 128    # Batch size in terms of number of sequences
shuffle = true      # Shuffle the dataset when sampling batches


# K-Means clusterer parameters
[clusterer]
n_clusters = 32     # Number of clusters/discrete action bins
max_iters = 100     # Maximum number of iterations for determining cluster centers
tol = 1e-4          # Tolerance for clustering early stopping if centers don't change 


# GPT-based policy parameters
[policy]
obs_dim = 514       # Observation dimension: image features (512) + prop. observations (2)
act_dim = 2         # Action dimension
n_bins = 32         # Number of clusters/discrete action bins
n_blocks = 3        # Number of successive Transformer blocks in GPT policy
embd_dim = 256      # Embedding dimension for Transformer blocks
n_heads = 4         # Number of attention heads in 
seq_len = 10        # Context/sequence-length for each sample and Transformer blocks
embd_pdrop = 0.6    # Dropout probability for input embeddings
attn_pdrop = 0.6    # Dropout probability for attention matrix
proj_pdrop = 0.6    # Dropout probability for attention output projection


# Trainer initialization parameters
[trainer.init]
gamma = 2.0             # Exponent for the (1 - p(t)) term in the focal loss function
max_grad_norm = 1.0     # Maximum allowed gradient norm before gradient norm clipping


# Trainer training parameters
[trainer.training]
n_epochs = 40           # Number of epochs to train Behavior Transformer model for
learning_rate = 1e-4    # Learning rate used by the AdamW optimizer
weight_decay = 1e-1     # Weight decay used by the AdamW optimizer
